"use client";
import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Loader2, RefreshCw, Search, Wallet, XCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase';

export default function BinsWithdrawalsPage() {
  const [rows,setRows]=useState<any[]>([]); const [holder,setHolder]=useState<any>(null); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [busy,setBusy]=useState('');
  const load=async()=>{setLoading(true);const [r,h]=await Promise.all([
    supabase.from('bins_withdrawal_requests').select('*,requester:profiles!bins_withdrawal_requests_requester_id_fkey(full_name,display_id,avatar_url),holder:bins_holder_accounts(display_id,name)').order('created_at',{ascending:false}).limit(500),
    supabase.from('bins_holder_accounts').select('*').limit(1).maybeSingle(),
  ]);setRows(r.data||[]);setHolder(h.data||null);setLoading(false)};
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>rows.filter(r=>(status==='all'||r.status===status)&&(!query.trim()||String(r.requester?.display_id||'').includes(query.trim())||(r.requester?.full_name||'').toLowerCase().includes(query.toLowerCase())||r.id.includes(query.trim()))),[rows,query,status]);
  const review=async(id:string,next:string)=>{setBusy(id+next);const note=window.prompt(`${next} note (optional)`)||null;const {data,error}=await supabase.rpc('admin_review_bins_withdrawal',{p_request_id:id,p_status:next,p_note:note});setBusy('');if(error||!data?.success)alert(data?.message||error?.message||'Failed');else void load()};
  return <div className="space-y-6">
    <div><h1 className="text-2xl font-black text-white flex items-center gap-2"><Wallet className="text-amber-400"/> Bins Holder Withdrawals</h1><p className="text-gray-500">Search, review and pay every host/agency-owner bins withdrawal.</p></div>
    <div className="grid md:grid-cols-3 gap-3">{[['Holder ID',holder?.display_id||990001],['Holder account',holder?.name||'Popular Live Bins Holder'],['Total bins received',Number(holder?.total_bins_received||0).toLocaleString()]].map(([l,v])=><div key={l} className="glass-card p-4"><p className="text-xs text-gray-500 uppercase">{l}</p><p className="text-xl font-black text-white mt-1">{v}</p></div>)}</div>
    <div className="flex gap-3 flex-wrap"><div className="relative"><Search className="absolute left-3 top-2.5 text-gray-500" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, user ID, request ID" className="bg-[#1E1A34] border border-white/10 rounded-xl pl-10 pr-4 py-2 text-white w-72"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="bg-[#1E1A34] border border-white/10 rounded-xl px-4 text-white"><option value="all">All statuses</option><option>pending</option><option>approved</option><option>paid</option><option>rejected</option></select><button onClick={()=>void load()} className="p-2 rounded-xl bg-white/5 text-gray-300"><RefreshCw size={18}/></button></div>
    <div className="glass-card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-gray-500 border-b border-white/10"><th className="p-4 text-left">Requester</th><th className="text-left">Request ID</th><th className="text-right">Bins / BDT</th><th>Status</th><th>Date</th><th className="text-right pr-4">Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-16"><Loader2 className="animate-spin mx-auto text-amber-400"/></td></tr>:filtered.map(r=><tr key={r.id} className="border-b border-white/5"><td className="p-4 text-white font-bold">{r.requester?.full_name||'User'}<div className="text-xs text-gray-500">ID {r.requester?.display_id||'—'} → Holder {r.holder?.display_id||990001}</div></td><td className="text-gray-400 font-mono text-xs">{r.id}</td><td className="text-right text-white font-bold">{Number(r.beans_amount).toLocaleString()}<div className="text-emerald-400">৳{Number(r.bdt_value).toLocaleString()}</div></td><td><span className="uppercase text-xs font-bold text-amber-300">{r.status}</span></td><td className="text-gray-400">{new Date(r.created_at).toLocaleString()}</td><td className="pr-4"><div className="flex justify-end gap-2">{r.status==='pending'&&<button disabled={!!busy} onClick={()=>void review(r.id,'approved')} className="p-2 bg-blue-500/15 text-blue-300 rounded-lg"><CheckCircle2 size={16}/></button>}{['pending','approved'].includes(r.status)&&<><button disabled={!!busy} onClick={()=>void review(r.id,'paid')} className="px-3 py-2 bg-emerald-500/15 text-emerald-300 rounded-lg font-bold">Pay</button><button disabled={!!busy} onClick={()=>void review(r.id,'rejected')} className="p-2 bg-red-500/15 text-red-300 rounded-lg"><XCircle size={16}/></button></>}</div></td></tr>)}</tbody></table></div>
  </div>;
}
