"use client";
import { useCallback, useEffect, useState } from 'react';
import { Check, Loader2, RefreshCw, Search, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Row = { id:string; user_id:string; requested_nickname:string; status:string; review_note?:string; created_at:string; user?:{full_name:string;display_id:number;avatar_url?:string} };

export default function NicknameApplicationsPage() {
  const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [busy,setBusy]=useState<string|null>(null);
  const load=useCallback(async()=>{ setLoading(true); const {data,error}=await supabase.from('nickname_applications').select('*,user:profiles!nickname_applications_user_id_fkey(full_name,display_id,avatar_url)').order('created_at',{ascending:false}).limit(200); if(error) alert(error.message); setRows((data as any[])||[]); setLoading(false); },[]);
  useEffect(()=>{ void load(); const ch=supabase.channel('admin-nickname-apps').on('postgres_changes',{event:'*',schema:'public',table:'nickname_applications'},load).subscribe(); return()=>{void supabase.removeChannel(ch)}; },[load]);
  async function review(row:Row,approve:boolean){ const note=approve?null:window.prompt('Rejection reason')||null; if(!approve&&!note)return; setBusy(row.id); const {data,error}=await supabase.rpc('admin_review_nickname_application',{p_application_id:row.id,p_approve:approve,p_note:note}); setBusy(null); if(error||!data?.success)alert(data?.message||error?.message); else await load(); }
  const q=search.toLowerCase(); const shown=rows.filter(r=>!q||r.requested_nickname.toLowerCase().includes(q)||r.user?.full_name?.toLowerCase().includes(q)||String(r.user?.display_id||'').includes(q));
  return <div className="space-y-6"><div className="flex justify-between gap-4 flex-wrap"><div><h1 className="text-3xl font-black text-white">Nickname Requests</h1><p className="text-gray-500 text-sm">Approve profile nickname badges. Duplicate nicknames are allowed.</p></div><button onClick={()=>void load()} className="p-3 rounded-xl bg-white/5 text-gray-300"><RefreshCw size={18}/></button></div>
    <div className="relative max-w-md"><Search className="absolute left-3 top-3 text-gray-500" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search user, ID or nickname" className="w-full bg-[#1E1A34] border border-white/10 rounded-xl pl-10 pr-4 py-2.5 text-white"/></div>
    <div className="glass-card overflow-hidden">{loading?<div className="p-20 flex justify-center"><Loader2 className="animate-spin text-pink-400"/></div>:shown.length===0?<p className="p-16 text-center text-gray-500">No nickname requests.</p>:shown.map(row=><div key={row.id} className="p-5 border-b border-white/5 flex items-center gap-4 flex-wrap"><div className="w-11 h-11 rounded-full bg-violet-500/20 flex items-center justify-center text-white font-black">{row.user?.full_name?.[0]||'U'}</div><div className="flex-1 min-w-48"><p className="text-white font-bold">{row.user?.full_name} <span className="text-gray-600 text-[10px] font-mono">ID {row.user?.display_id}</span></p><p className="text-xl text-pink-300 font-black">{row.requested_nickname}</p><p className="text-[10px] text-gray-600">{new Date(row.created_at).toLocaleString()} · {row.status}</p></div>{row.status==='pending'?<><button disabled={busy===row.id} onClick={()=>void review(row,true)} className="p-2.5 rounded-xl bg-emerald-500/15 text-emerald-300"><Check/></button><button disabled={busy===row.id} onClick={()=>void review(row,false)} className="p-2.5 rounded-xl bg-rose-500/15 text-rose-300"><X/></button></>:<span className="text-xs uppercase text-gray-500 font-bold">{row.status}</span>}</div>)}</div>
  </div>;
}
